version: '3.8'

services:
  mysql:
    image: mysql:5.7  
    container_name: tutorial-mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: devpassword  
      MYSQL_DATABASE: devdatabase 
      MYSQL_USER: devuser  
      MYSQL_PASSWORD: devpassword  
    ports:
      - "3306:3306"  
    volumes:
      - mysql-data:/var/lib/mysql  

volumes:
  mysql-data:
    driver: local  